---
- name: Provision OpenNebula Front End on CentOS
  hosts: front-end
  become: yes
  strategy: debug

  roles:

    - role: selinux
      become: yes
      tags: selinux

<<<<<<< HEAD
    - role: epel
      become: yes
      tags: epel

=======
>>>>>>> 1f2e5d596ccc27400c5b266f83fccdda89cb9aaf
    - role: repo
      become: yes
      tags: repo
      
    - role: mariadb
      become: yes
      tags: mariadb

<<<<<<< HEAD
    - role: ruby
      become: yes
      tags: ruby

=======
>>>>>>> 1f2e5d596ccc27400c5b266f83fccdda89cb9aaf
    - role: front-end
      become: yes
      tags: front-end

    
