---

- name: Install OpenNebula Node Package
  yum:
    name:
      - opennebula-node-kvm
      - bridge-utils
    state: present

- name: Restart libvirtd
  systemd:
    name: libvirtd
    state: restarted

- name: Install centos-release-qemu-ev
  yum:
    name: centos-release-qemu-ev
    state: present
  
- name: Install QEMU
  yum:
    name:
      - qemu-kvm-ev
    state: latest

- name: Enable and start Libvirt and messagebus
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - messagebus.service
    - libvirtd.service
    
- name: Copy bridge configuration file
  template:
    src: bridge-config-dhcp.j2
    dest: /etc/sysconfig/network-scripts/{{ BRIDGE_INTERFACE }}
    owner: root
    group: root
    mode: 0755
    backup: yes
  tags: vnet
    
- name: Restart network service
  service: 
    name: network 
    state: restarted
  tags: vnet

